//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controles: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""Wheel"",
            ""id"": ""41913963-8832-4059-aa74-7a8e43c1e062"",
            ""actions"": [
                {
                    ""name"": ""Direccion"",
                    ""type"": ""Value"",
                    ""id"": ""600cf519-f6f3-4b55-9a58-63200839c03b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acelerador"",
                    ""type"": ""Value"",
                    ""id"": ""d0d03e81-2295-4535-8807-34942e53b09f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Freno"",
                    ""type"": ""Button"",
                    ""id"": ""40153fac-6d4a-4bc9-9bbd-f5bb7d546bc7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Embrague"",
                    ""type"": ""Value"",
                    ""id"": ""fdf41f65-ce4f-44b3-9bfe-11177dc6201a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Marcha 1"",
                    ""type"": ""Button"",
                    ""id"": ""ae785bfc-0775-4d39-9d40-dd6fa2b5c5cb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Marcha 2"",
                    ""type"": ""Button"",
                    ""id"": ""f26c2509-099c-45a1-8dc3-259ce29c8d93"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disparar"",
                    ""type"": ""Button"",
                    ""id"": ""188d559e-d2f8-48ab-80f1-2a49ab937114"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disparar 2"",
                    ""type"": ""Button"",
                    ""id"": ""36dde45c-3f75-42b8-bcea-c92fe3c1b945"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""56fef8e7-bc63-4159-9b80-29518778b76a"",
                    ""path"": ""<HID::G25 Racing Wheel>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Auto"",
                    ""action"": ""Direccion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""778aa74e-78a1-433d-805e-33d4b6f8d6c8"",
                    ""path"": ""<HID::G25 Racing Wheel>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acelerador"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82840f51-197a-482f-b945-6581b0f16eb7"",
                    ""path"": ""<HID::G25 Racing Wheel>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Freno"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fd016fb-2738-490e-a956-313f24ba74c4"",
                    ""path"": ""<HID::G25 Racing Wheel>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Marcha 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d794ef5-1fbf-40be-b4cc-070e4cceedea"",
                    ""path"": ""<HID::G25 Racing Wheel>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Marcha 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bca01989-3578-48a5-ba58-36886ec919c7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Embrague"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b537b805-db5a-47bf-aece-86a1c074e06c"",
                    ""path"": ""<HID::G25 Racing Wheel>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aaa0a36-6d04-4858-9f83-b2e66171d929"",
                    ""path"": ""<HID::G25 Racing Wheel>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Auto"",
            ""bindingGroup"": ""Auto"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::G25 Racing Wheel>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Auto1"",
            ""bindingGroup"": ""Auto1"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::G25 Racing Wheel>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Wheel
        m_Wheel = asset.FindActionMap("Wheel", throwIfNotFound: true);
        m_Wheel_Direccion = m_Wheel.FindAction("Direccion", throwIfNotFound: true);
        m_Wheel_Acelerador = m_Wheel.FindAction("Acelerador", throwIfNotFound: true);
        m_Wheel_Freno = m_Wheel.FindAction("Freno", throwIfNotFound: true);
        m_Wheel_Embrague = m_Wheel.FindAction("Embrague", throwIfNotFound: true);
        m_Wheel_Marcha1 = m_Wheel.FindAction("Marcha 1", throwIfNotFound: true);
        m_Wheel_Marcha2 = m_Wheel.FindAction("Marcha 2", throwIfNotFound: true);
        m_Wheel_Disparar = m_Wheel.FindAction("Disparar", throwIfNotFound: true);
        m_Wheel_Disparar2 = m_Wheel.FindAction("Disparar 2", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_Wheel.enabled, "This will cause a leak and performance issues, Controles.Wheel.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Wheel
    private readonly InputActionMap m_Wheel;
    private List<IWheelActions> m_WheelActionsCallbackInterfaces = new List<IWheelActions>();
    private readonly InputAction m_Wheel_Direccion;
    private readonly InputAction m_Wheel_Acelerador;
    private readonly InputAction m_Wheel_Freno;
    private readonly InputAction m_Wheel_Embrague;
    private readonly InputAction m_Wheel_Marcha1;
    private readonly InputAction m_Wheel_Marcha2;
    private readonly InputAction m_Wheel_Disparar;
    private readonly InputAction m_Wheel_Disparar2;
    public struct WheelActions
    {
        private @Controles m_Wrapper;
        public WheelActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Direccion => m_Wrapper.m_Wheel_Direccion;
        public InputAction @Acelerador => m_Wrapper.m_Wheel_Acelerador;
        public InputAction @Freno => m_Wrapper.m_Wheel_Freno;
        public InputAction @Embrague => m_Wrapper.m_Wheel_Embrague;
        public InputAction @Marcha1 => m_Wrapper.m_Wheel_Marcha1;
        public InputAction @Marcha2 => m_Wrapper.m_Wheel_Marcha2;
        public InputAction @Disparar => m_Wrapper.m_Wheel_Disparar;
        public InputAction @Disparar2 => m_Wrapper.m_Wheel_Disparar2;
        public InputActionMap Get() { return m_Wrapper.m_Wheel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WheelActions set) { return set.Get(); }
        public void AddCallbacks(IWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_WheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WheelActionsCallbackInterfaces.Add(instance);
            @Direccion.started += instance.OnDireccion;
            @Direccion.performed += instance.OnDireccion;
            @Direccion.canceled += instance.OnDireccion;
            @Acelerador.started += instance.OnAcelerador;
            @Acelerador.performed += instance.OnAcelerador;
            @Acelerador.canceled += instance.OnAcelerador;
            @Freno.started += instance.OnFreno;
            @Freno.performed += instance.OnFreno;
            @Freno.canceled += instance.OnFreno;
            @Embrague.started += instance.OnEmbrague;
            @Embrague.performed += instance.OnEmbrague;
            @Embrague.canceled += instance.OnEmbrague;
            @Marcha1.started += instance.OnMarcha1;
            @Marcha1.performed += instance.OnMarcha1;
            @Marcha1.canceled += instance.OnMarcha1;
            @Marcha2.started += instance.OnMarcha2;
            @Marcha2.performed += instance.OnMarcha2;
            @Marcha2.canceled += instance.OnMarcha2;
            @Disparar.started += instance.OnDisparar;
            @Disparar.performed += instance.OnDisparar;
            @Disparar.canceled += instance.OnDisparar;
            @Disparar2.started += instance.OnDisparar2;
            @Disparar2.performed += instance.OnDisparar2;
            @Disparar2.canceled += instance.OnDisparar2;
        }

        private void UnregisterCallbacks(IWheelActions instance)
        {
            @Direccion.started -= instance.OnDireccion;
            @Direccion.performed -= instance.OnDireccion;
            @Direccion.canceled -= instance.OnDireccion;
            @Acelerador.started -= instance.OnAcelerador;
            @Acelerador.performed -= instance.OnAcelerador;
            @Acelerador.canceled -= instance.OnAcelerador;
            @Freno.started -= instance.OnFreno;
            @Freno.performed -= instance.OnFreno;
            @Freno.canceled -= instance.OnFreno;
            @Embrague.started -= instance.OnEmbrague;
            @Embrague.performed -= instance.OnEmbrague;
            @Embrague.canceled -= instance.OnEmbrague;
            @Marcha1.started -= instance.OnMarcha1;
            @Marcha1.performed -= instance.OnMarcha1;
            @Marcha1.canceled -= instance.OnMarcha1;
            @Marcha2.started -= instance.OnMarcha2;
            @Marcha2.performed -= instance.OnMarcha2;
            @Marcha2.canceled -= instance.OnMarcha2;
            @Disparar.started -= instance.OnDisparar;
            @Disparar.performed -= instance.OnDisparar;
            @Disparar.canceled -= instance.OnDisparar;
            @Disparar2.started -= instance.OnDisparar2;
            @Disparar2.performed -= instance.OnDisparar2;
            @Disparar2.canceled -= instance.OnDisparar2;
        }

        public void RemoveCallbacks(IWheelActions instance)
        {
            if (m_Wrapper.m_WheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_WheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WheelActions @Wheel => new WheelActions(this);
    private int m_AutoSchemeIndex = -1;
    public InputControlScheme AutoScheme
    {
        get
        {
            if (m_AutoSchemeIndex == -1) m_AutoSchemeIndex = asset.FindControlSchemeIndex("Auto");
            return asset.controlSchemes[m_AutoSchemeIndex];
        }
    }
    private int m_Auto1SchemeIndex = -1;
    public InputControlScheme Auto1Scheme
    {
        get
        {
            if (m_Auto1SchemeIndex == -1) m_Auto1SchemeIndex = asset.FindControlSchemeIndex("Auto1");
            return asset.controlSchemes[m_Auto1SchemeIndex];
        }
    }
    public interface IWheelActions
    {
        void OnDireccion(InputAction.CallbackContext context);
        void OnAcelerador(InputAction.CallbackContext context);
        void OnFreno(InputAction.CallbackContext context);
        void OnEmbrague(InputAction.CallbackContext context);
        void OnMarcha1(InputAction.CallbackContext context);
        void OnMarcha2(InputAction.CallbackContext context);
        void OnDisparar(InputAction.CallbackContext context);
        void OnDisparar2(InputAction.CallbackContext context);
    }
}
